export const RETRIEVE_STUDENTS = "RETRIEVE_STUDENTS";
export const SHOW_STUDENT = "SHOW_STUDENT";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const DELETE_ALL_STUDENT = "DELETE_ALL_STUDENT";




